### ISSUE TITLE
Obfuscated plain-text-mail-addresses

### ISSUE THREAD

**Issue by sebastian-marinescu** [Jako/emo-evo#1]
Hi Jako, 
after testing your plugin I noticed that obfuscated plain-text-mail-addresses are converted to a mailto-link at insertion. I think it should either be an option to generated links out of emails, or better yet the plain-text-mails remain plain-text. What do you think?

**Comment by Jako** [comment]
Thats a good idea for an enhancement but it is posted on the wrong github repository.

**Comment by sebastian-marinescu** [comment]
I was wondering, thanks :+1:
