### ISSUE TITLE
Parse Error with PHP7

### ISSUE THREAD

**Issue by Netzfeld** [Jako/emo-evo#2]
Error : preg_replace(): The /e modifier is no longer supported, use preg_replace_callback instead
assets/plugins/emo/emo.class.php, Line 166
`$matches[1] = preg_replace('!(.*\?(subject|body)=)([^\?]*)!ie', "'$1'.rawurldecode(rawurlencode('$3'))", $matches[1]);`

does anyone know how to fix it?

**Comment by Jako** [comment]
Please try the fix in the commit.
